name: Test
on:
  push:
    branches:
        - "master"

jobs:
    delete_open_scratch_logs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install sf cli
              run: |
                npm install sfdx-cli
                node_modules/sfdx-cli/bin/run --version
                node_modules/sfdx-cli/bin/run plugins --core
            - name: Get the username
              run: |
                echo "${{ env.USERNAME }}"
                env
              env:
                USERNAME: jq .result.username ./test.json | xargs
        
