name: Test
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'

jobs:
    delete_open_scratch_logs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install sf cli
              run: |
                npm install sfdx-cli
                node_modules/sfdx-cli/bin/run --version
                node_modules/sfdx-cli/bin/run plugins --core
            - name: Get the username
              run: |
                echo "USERNAME=$(jq .result.username ./test.json | xargs)" >> $GITHUB_ENV
            - name: Test
              run: echo $USERNAME
            - name: Do something
              if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
              run: echo "hello"
                  
              
        
