name: Test
on:
    pull_request:
        types: [closed]

# env:
#     PR_NUMBER: ${{ github.event.pull_request.number }}
#     BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
jobs:
    delete_open_scratch_logs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install sf
              run: |
                wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
                mkdir ~/cli/sf
                tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1
                export PATH=~/cli/sf/bin:$PATH
                PATH=~/cli/sf/bin:$PATH
                ~/cli/sf/bin/sf --version
                env
            - name: Create key file
              run: |
                echo "$TOKEN" > file.key
                cat file.key
            
            # - name: Install sf cli
            #   run: |
            #     npm install sfdx-cli
            #     node_modules/sfdx-cli/bin/run --version
            #     node_modules/sfdx-cli/bin/run plugins --core
            
            # - name: Extract and Set Environment Variable
            #   run: |
            #     full_string="${{ github.event.pull_request.number }}${{ github.event.pull_request.head.ref }}"
            #     substring="${full_string:0:80}"
            #     echo "PR_ENV_VAR=$substring" >> $GITHUB_ENV
      
            # - name: Use Environment Variable
            #   run: |
            #     echo $PR_ENV_VAR
            #     echo ${{ vars.TEST_VAR }}
            # - name: Secret
            #   run: |
            #     echo ${{secrets.TOKEN}} | sed 's/./& /g'


