name: Test
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

# env:
#   TRIGGER: ${{ inputs.trigger }}
#   desciption: ${{ inputs.desciption }}

jobs:
    delete_open_scratch_logs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install sf cli
              run: |
                npm install sfdx-cli
                node_modules/sfdx-cli/bin/run --version
                node_modules/sfdx-cli/bin/run plugins --core
            - name: Get the username
              run: |
                echo "USERNAME=$(jq .result.username ./test.json | xargs)" >> $GITHUB_ENV
            - name: Test
              run: echo $USERNAME
                  
              
        
