name: Test
on:
    pull_request:
        types: [closed]
    # push:
    #     branches:
    #     - '12feature-srini-Expire-Conditional@test-Offer-before-Deposit-cannot-be-scheduled-in-time-to-make-affordable'

# env:
#     PR_NUMBER: ${{ github.event.pull_request.number }}
#     BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
jobs:
    delete_open_scratch_logs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install sf
              run: |
                wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
                mkdir -p ~/cli/sf
                tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1
                ~/cli/sf/bin/sf --version
            
            - name: Extract and Set Environment Variable
              run: |
                full_string="${{ github.event.pull_request.number }}NG${{ github.event.pull_request.head.ref }}"
                substring=$(echo $full_string | sed 's/[^a-zA-Z0-9-]/-/g')
                echo $substring
                substring="${substring:0:80}"
                echo "PR_ENV_VAR=$substring" >> $GITHUB_ENV
      
            - name: Use Environment Variable
              run: |
                echo $PR_ENV_VAR
            # - name: Secret
            #   run: |
            #     echo ${{secrets.TOKEN}} | sed 's/./& /g'


