name: Test
on:
    pull_request:
        types: [closed]

env:
    PR_NUMBER: ${{ github.event.pull_request.number }}
    BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
jobs:
    delete_open_scratch_logs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Install sf cli
              run: |
                npm install sfdx-cli
                node_modules/sfdx-cli/bin/run --version
                node_modules/sfdx-cli/bin/run plugins --core
            
            - name: Env
              run: echo ${{ github.event.pull_request.number }}${{ github.event.pull_request.head.ref }}
        

