name: Test
on:
  pull_request:
    branches-ignore:
      - "dependabot-updates"
    types: [closed]

jobs:
    # delete_open_scratch_logs:
    if_merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install sf cli
              run: |
                npm install sfdx-cli
                node_modules/sfdx-cli/bin/run --version
                node_modules/sfdx-cli/bin/run plugins --core
            - name: Check the cli 
              run: node_modules/sfdx-cli/bin/run --version
